name: pos_offline_desktop
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  package_info_plus: ^8.3.0
  open_file_plus: ^3.4.1+1
  gap: ^3.0.1
  path_provider: ^2.1.5
  path: ^1.9.1
  excel: ^4.0.6
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.2
  number_to_words: ^1.0.0
  go_router: ^16.0.0
  flutter_localization: ^0.3.3

  cupertino_icons: ^1.0.8

  pdf: ^3.11.3
  printing: ^5.14.2

  desktop_window: ^0.4.2

  drift: ^2.26.0
  drift_flutter: ^0.2.4

  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

  flutter_lints: ^6.0.0

flutter: 
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
